# Generated by Django 3.1.6 on 2021-02-08 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20210207_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 2, 7, 16, 19, 26, 490290)),
        ),
    ]
