# Generated by Django 3.1.6 on 2021-02-08 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20210207_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='info',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 2, 7, 16, 23, 3, 416311)),
        ),
    ]
